import { 
  Room, 
  Reservation, 
  Guest, 
  Folio, 
  HousekeepingTask, 
  MaintenanceWorkOrder, 
  DepartmentChannel, 
  InternalMessage, 
  ShiftLog, 
  FnBItem, 
  FnBOrder, 
  InventoryItem, 
  PurchaseOrder, 
  StaffMember, 
  NightAuditRecord,
  UserRoleProfile 
} from "./types";

export const USER_ROLES: UserRoleProfile[] = [
  {
    role: "GENERAL_MANAGER",
    title: "General Manager & Executive",
    name: "Alexander Hartanto, CHA",
    department: "Executive Committee",
    badgeColor: "bg-emerald-800 text-white",
    description: "Full oversight over hotel revenue, operational KPIs, multi-department sync, and strategic Capex.",
  },
  {
    role: "FRONT_OFFICE_MANAGER",
    title: "Front Office Manager",
    name: "Dewi Lestari",
    department: "Front Desk & Guest Services",
    badgeColor: "bg-teal-700 text-white",
    description: "Manages check-ins, guest arrivals/departures, room assignments, keycards, and guest CRM.",
  },
  {
    role: "EXECUTIVE_HOUSEKEEPER",
    title: "Executive Housekeeper",
    name: "Siti Rahmawati",
    department: "Housekeeping & Facilities",
    badgeColor: "bg-amber-700 text-white",
    description: "Oversees room turnaround, cleanliness inspections, linen par stock, and room attendant assignments.",
  },
  {
    role: "CHIEF_ENGINEER",
    title: "Chief Engineer",
    name: "Bambang Wibowo, ST",
    department: "Engineering & Maintenance",
    badgeColor: "bg-stone-700 text-white",
    description: "Dispatches technical work orders, HVAC monitoring, preventive maintenance, and safety audits.",
  },
  {
    role: "FINANCIAL_CONTROLLER",
    title: "Financial Controller",
    name: "Victoria Wijaya, CPA",
    department: "Finance & Night Audit",
    badgeColor: "bg-emerald-900 text-white",
    description: "Manages daily flash reports, night audits, city ledgers, tax settlements, and P&L statements.",
  },
  {
    role: "HR_DIRECTOR",
    title: "Director of Human Resources",
    name: "Rian Pratama, SH",
    department: "People & Talent",
    badgeColor: "bg-cyan-800 text-white",
    description: "Coordinates staff shift rosters, attendance, training certifications, and departmental KPIs.",
  }
];

export const INITIAL_ROOMS: Room[] = [
  // Floor 1 - Deluxe & Pool Access
  {
    id: "rm-101",
    roomNumber: "101",
    floor: 1,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "OCCUPIED",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Wayan Sudir",
    currentGuestName: "Dr. Jonathan Lee",
    currentReservationId: "res-001",
    keycardCount: 2,
    lastCleanedAt: "2026-08-24 10:30",
    amenities: ["Pool Access", "Nespresso Machine", "Marble Bath", "Smart TV 55\"", "High-Speed Wi-Fi"],
  },
  {
    id: "rm-102",
    roomNumber: "102",
    floor: 1,
    category: "Superior Twin",
    basePrice: 1100000,
    currentRate: 1100000,
    status: "VACANT_DIRTY",
    bedType: "Twin Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Ratna Sari",
    lastCleanedAt: "2026-08-23 16:00",
    amenities: ["Garden View", "Rain Shower", "Mini Fridge", "Smart TV 50\""],
  },
  {
    id: "rm-103",
    roomNumber: "103",
    floor: 1,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "VACANT_INSPECTED",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Wayan Sudir",
    lastCleanedAt: "2026-08-24 11:15",
    amenities: ["Pool Access", "Nespresso Machine", "Balcony", "Smart TV 55\""],
  },
  {
    id: "rm-104",
    roomNumber: "104",
    floor: 1,
    category: "Superior Twin",
    basePrice: 1100000,
    currentRate: 1150000,
    status: "OCCUPIED",
    bedType: "Twin Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Ratna Sari",
    currentGuestName: "Clara Tanaka",
    currentReservationId: "res-002",
    keycardCount: 2,
    lastCleanedAt: "2026-08-24 09:45",
    amenities: ["Garden View", "Rain Shower", "Work Desk"],
  },
  {
    id: "rm-105",
    roomNumber: "105",
    floor: 1,
    category: "Garden Pool Villa",
    basePrice: 3200000,
    currentRate: 3500000,
    status: "OCCUPIED",
    bedType: "Super King",
    maxOccupancy: 4,
    assignedHousekeeper: "Made Wirya",
    currentGuestName: "H. Salim Effendi (VVIP)",
    currentReservationId: "res-003",
    keycardCount: 3,
    lastCleanedAt: "2026-08-24 08:30",
    amenities: ["Private Plunge Pool", "Gazebo", "Butler Service", "Sub-Zero Wine Chiller", "Sonos Soundbar"],
  },
  {
    id: "rm-106",
    roomNumber: "106",
    floor: 1,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1350000,
    status: "RESERVED",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Wayan Sudir",
    lastCleanedAt: "2026-08-24 12:00",
    amenities: ["Pool View", "Deep Soaking Tub", "Complimentary Minibar"],
  },

  // Floor 2
  {
    id: "rm-201",
    roomNumber: "201",
    floor: 2,
    category: "Executive Suite",
    basePrice: 2200000,
    currentRate: 2400000,
    status: "OCCUPIED",
    bedType: "Super King",
    maxOccupancy: 3,
    assignedHousekeeper: "Budi Santoso",
    currentGuestName: "Marcus Vance",
    currentReservationId: "res-004",
    keycardCount: 2,
    lastCleanedAt: "2026-08-24 10:00",
    amenities: ["Executive Lounge Access", "Separate Living Room", "Espresso Bar", "Dyson Hair Dryer"],
  },
  {
    id: "rm-202",
    roomNumber: "202",
    floor: 2,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "DUE_OUT",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Budi Santoso",
    currentGuestName: "Sarah Jenkins",
    currentReservationId: "res-005",
    keycardCount: 1,
    lastCleanedAt: "2026-08-23 11:30",
    amenities: ["Courtyard View", "Rain Shower", "Work Desk Ergonomic"],
  },
  {
    id: "rm-203",
    roomNumber: "203",
    floor: 2,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "IN_PROGRESS",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Ratna Sari",
    lastCleanedAt: "2026-08-24 13:10",
    amenities: ["City View", "Bathtub", "Smart TV 55\""],
  },
  {
    id: "rm-204",
    roomNumber: "204",
    floor: 2,
    category: "Superior Twin",
    basePrice: 1100000,
    currentRate: 1150000,
    status: "VACANT_CLEAN",
    bedType: "Twin Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Ratna Sari",
    lastCleanedAt: "2026-08-24 11:00",
    amenities: ["Courtyard View", "Rain Shower"],
  },
  {
    id: "rm-205",
    roomNumber: "205",
    floor: 2,
    category: "Executive Suite",
    basePrice: 2200000,
    currentRate: 2400000,
    status: "OCCUPIED",
    bedType: "Super King",
    maxOccupancy: 3,
    assignedHousekeeper: "Budi Santoso",
    currentGuestName: "Ir. Hendra Gunawan",
    currentReservationId: "res-006",
    keycardCount: 2,
    lastCleanedAt: "2026-08-24 09:15",
    amenities: ["Executive Lounge Access", "Living Room", "Walk-in Wardrobe"],
  },
  {
    id: "rm-206",
    roomNumber: "206",
    floor: 2,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "OUT_OF_ORDER",
    bedType: "King Bed",
    maxOccupancy: 2,
    notes: "AC compressor replacement in progress by Engineering (Ticket #ENG-304)",
    amenities: ["Courtyard View", "Balcony"],
  },

  // Floor 3
  {
    id: "rm-301",
    roomNumber: "301",
    floor: 3,
    category: "Executive Suite",
    basePrice: 2200000,
    currentRate: 2500000,
    status: "OCCUPIED",
    bedType: "Super King",
    maxOccupancy: 3,
    assignedHousekeeper: "Made Wirya",
    currentGuestName: "Sophia Chen",
    currentReservationId: "res-007",
    keycardCount: 2,
    lastCleanedAt: "2026-08-24 10:45",
    amenities: ["Panoramic Skyline", "Executive Lounge", "Jacuzzi Tub", "Bose Sound"],
  },
  {
    id: "rm-302",
    roomNumber: "302",
    floor: 3,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "OCCUPIED",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Made Wirya",
    currentGuestName: "Dmitry Morozov",
    currentReservationId: "res-008",
    keycardCount: 1,
    lastCleanedAt: "2026-08-24 11:20",
    amenities: ["High Floor Skyline", "Rain Shower", "Premium Minibar"],
  },
  {
    id: "rm-303",
    roomNumber: "303",
    floor: 3,
    category: "Superior Twin",
    basePrice: 1100000,
    currentRate: 1200000,
    status: "VACANT_INSPECTED",
    bedType: "Twin Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Siti Rahmawati",
    lastCleanedAt: "2026-08-24 12:40",
    amenities: ["City View", "Rain Shower", "Coffee Machine"],
  },
  {
    id: "rm-304",
    roomNumber: "304",
    floor: 3,
    category: "Deluxe King",
    basePrice: 1350000,
    currentRate: 1450000,
    status: "VACANT_CLEAN",
    bedType: "King Bed",
    maxOccupancy: 2,
    assignedHousekeeper: "Wayan Sudir",
    lastCleanedAt: "2026-08-24 12:10",
    amenities: ["Skyline View", "Smart TV 55\"", "Luxury Linens"],
  },

  // Floor 4 - Penthouses & Presidential
  {
    id: "rm-401",
    roomNumber: "401",
    floor: 4,
    category: "Grand Penthouse",
    basePrice: 5500000,
    currentRate: 6200000,
    status: "OCCUPIED",
    bedType: "Super King",
    maxOccupancy: 4,
    assignedHousekeeper: "Siti Rahmawati",
    currentGuestName: "Tan Sri Dato' Vincent Khoo (VIP Platinum)",
    currentReservationId: "res-009",
    keycardCount: 4,
    lastCleanedAt: "2026-08-24 09:00",
    amenities: ["Private Rooftop Terrace", "Infinity Jacuzzi", "Dedicated Butler", "Private Dining Salon", "Grand Piano"],
  },
  {
    id: "rm-402",
    roomNumber: "402",
    floor: 4,
    category: "Grand Penthouse",
    basePrice: 5500000,
    currentRate: 5800000,
    status: "VACANT_INSPECTED",
    bedType: "Super King",
    maxOccupancy: 4,
    assignedHousekeeper: "Siti Rahmawati",
    lastCleanedAt: "2026-08-24 11:50",
    amenities: ["Rooftop Terrace", "Panoramic Jacuzzi", "Butler Pantry", "B&O Audio"],
  }
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: "gst-001",
    fullName: "Dr. Jonathan Lee",
    email: "j.lee@singapore-med.org",
    phone: "+65 9123 4567",
    idNumber: "E4988219A",
    nationality: "Singapore",
    vipLevel: "GOLD",
    totalStays: 6,
    lifetimeSpend: 24500000,
    preferences: ["High Floor", "Extra firm pillow", "Daily Financial Times", "Decaf Nespresso pods"],
    dietaryRestrictions: "Gluten Sensitive",
    notes: "Frequent medical conference attendee. Prefers quiet pool side view.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gst-002",
    fullName: "Clara Tanaka",
    email: "clara.tanaka@tokyo-design.jp",
    phone: "+81 90 8821 9912",
    idNumber: "TR8849102",
    nationality: "Japan",
    vipLevel: "SILVER",
    totalStays: 3,
    lifetimeSpend: 11800000,
    preferences: ["Late Check-out 14:00", "Green Tea amenities", "Humidifier in room"],
    dietaryRestrictions: "Vegetarian",
    notes: "Architecture consultant. Loves heritage woodwork aesthetics.",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gst-003",
    fullName: "H. Salim Effendi",
    email: "salim.effendi@effendicorp.id",
    phone: "+62 811 9928 111",
    idNumber: "3171041908750002",
    nationality: "Indonesia",
    vipLevel: "VVIP",
    totalStays: 14,
    lifetimeSpend: 86400000,
    preferences: ["Garden Pool Villa exclusive", "Personal Chef on standby", "BMW 7-Series Airport Transfer", "Sparkling San Pellegrino"],
    notes: "Owner of industrial conglomerate. VIP welcoming protocol required with GM greeting.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gst-004",
    fullName: "Marcus Vance",
    email: "marcus.vance@venture-peak.com",
    phone: "+1 415 892 0019",
    idNumber: "USA-5991029",
    nationality: "United States",
    vipLevel: "PLATINUM",
    totalStays: 9,
    lifetimeSpend: 42300000,
    preferences: ["Executive Lounge meeting room access", "Ironing board setup on arrival", "Cold Brew coffee at 07:00"],
    notes: "Managing Partner at tech VC fund.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "gst-005",
    fullName: "Tan Sri Dato' Vincent Khoo",
    email: "vkhoo@khoo-holdings.my",
    phone: "+60 12 334 9876",
    idNumber: "MY-A994012",
    nationality: "Malaysia",
    vipLevel: "VVIP",
    totalStays: 18,
    lifetimeSpend: 138000000,
    preferences: ["Grand Penthouse 401 only", "Rooftop dining tasting menu", "Private security clearance"],
    notes: "Chairman of Khoo Investment Group. VIP champagne & fruit basket greeting mandatory.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
  }
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: "res-001",
    bookingCode: "MXZ-2608-8812",
    guestId: "gst-001",
    guestName: "Dr. Jonathan Lee",
    guestEmail: "j.lee@singapore-med.org",
    guestPhone: "+65 9123 4567",
    vipLevel: "GOLD",
    roomId: "rm-101",
    roomNumber: "101",
    category: "Deluxe King",
    checkInDate: "2026-08-23",
    checkOutDate: "2026-08-26",
    nights: 3,
    adults: 2,
    children: 0,
    channel: "DIRECT_WEB",
    status: "CHECKED_IN",
    totalAmount: 4350000,
    depositPaid: 2000000,
    balanceDue: 2350000,
    specialRequests: "Quiet room near pool, feather-free pillows.",
    createdAt: "2026-08-10 14:22",
    folioId: "fol-001",
  },
  {
    id: "res-002",
    bookingCode: "MXZ-2608-8815",
    guestId: "gst-002",
    guestName: "Clara Tanaka",
    guestEmail: "clara.tanaka@tokyo-design.jp",
    guestPhone: "+81 90 8821 9912",
    vipLevel: "SILVER",
    roomId: "rm-104",
    roomNumber: "104",
    category: "Superior Twin",
    checkInDate: "2026-08-24",
    checkOutDate: "2026-08-27",
    nights: 3,
    adults: 1,
    children: 0,
    channel: "BOOKING_COM",
    status: "CHECKED_IN",
    totalAmount: 3450000,
    depositPaid: 3450000,
    balanceDue: 0,
    specialRequests: "Non-smoking room, high tea voucher.",
    createdAt: "2026-08-18 09:12",
    folioId: "fol-002",
  },
  {
    id: "res-003",
    bookingCode: "MXZ-2608-8820",
    guestId: "gst-003",
    guestName: "H. Salim Effendi",
    guestEmail: "salim.effendi@effendicorp.id",
    guestPhone: "+62 811 9928 111",
    vipLevel: "VVIP",
    roomId: "rm-105",
    roomNumber: "105",
    category: "Garden Pool Villa",
    checkInDate: "2026-08-22",
    checkOutDate: "2026-08-25",
    nights: 3,
    adults: 2,
    children: 2,
    channel: "CORPORATE_MICE",
    status: "CHECKED_IN",
    totalAmount: 10500000,
    depositPaid: 10500000,
    balanceDue: 0,
    specialRequests: "Villa butler, late checkout requested.",
    createdAt: "2026-08-01 11:30",
    folioId: "fol-003",
  },
  {
    id: "res-004",
    bookingCode: "MXZ-2608-8831",
    guestId: "gst-004",
    guestName: "Marcus Vance",
    guestEmail: "marcus.vance@venture-peak.com",
    guestPhone: "+1 415 892 0019",
    vipLevel: "PLATINUM",
    roomId: "rm-201",
    roomNumber: "201",
    category: "Executive Suite",
    checkInDate: "2026-08-24",
    checkOutDate: "2026-08-28",
    nights: 4,
    adults: 1,
    children: 0,
    channel: "AGODA",
    status: "CHECKED_IN",
    totalAmount: 9600000,
    depositPaid: 5000000,
    balanceDue: 4600000,
    specialRequests: "Airport BMW pickup requested, invoice to corporate tax ID.",
    createdAt: "2026-08-14 16:45",
    folioId: "fol-004",
  },
  {
    id: "res-005",
    bookingCode: "MXZ-2608-8840",
    guestId: "gst-005",
    guestName: "Tan Sri Dato' Vincent Khoo",
    guestEmail: "vkhoo@khoo-holdings.my",
    guestPhone: "+60 12 334 9876",
    vipLevel: "VVIP",
    roomId: "rm-401",
    roomNumber: "401",
    category: "Grand Penthouse",
    checkInDate: "2026-08-23",
    checkOutDate: "2026-08-26",
    nights: 3,
    adults: 2,
    children: 0,
    channel: "DIRECT_WEB",
    status: "CHECKED_IN",
    totalAmount: 18600000,
    depositPaid: 18600000,
    balanceDue: 0,
    specialRequests: "Penthouse setup, GM in-person welcome.",
    createdAt: "2026-08-05 10:00",
    folioId: "fol-005",
  },
  {
    id: "res-006",
    bookingCode: "MXZ-2608-8855",
    guestId: "gst-006",
    guestName: "Ir. Hendra Gunawan",
    guestEmail: "hendra.gunawan@triputra.co.id",
    guestPhone: "+62 812 8871 009",
    vipLevel: "GOLD",
    roomId: "rm-205",
    roomNumber: "205",
    category: "Executive Suite",
    checkInDate: "2026-08-24",
    checkOutDate: "2026-08-27",
    nights: 3,
    adults: 2,
    children: 1,
    channel: "WALK_IN",
    status: "CHECKED_IN",
    totalAmount: 7200000,
    depositPaid: 7200000,
    balanceDue: 0,
    specialRequests: "Baby cot setup in living room.",
    createdAt: "2026-08-24 11:00",
    folioId: "fol-006",
  },
  {
    id: "res-007",
    bookingCode: "MXZ-2608-8890",
    guestId: "gst-007",
    guestName: "Amanda Valerie",
    guestEmail: "amanda.val@gmail.com",
    guestPhone: "+62 818 0912 334",
    vipLevel: "STANDARD",
    roomId: "rm-106",
    roomNumber: "106",
    category: "Deluxe King",
    checkInDate: "2026-08-24",
    checkOutDate: "2026-08-26",
    nights: 2,
    adults: 2,
    children: 0,
    channel: "EXPEDIA",
    status: "CONFIRMED",
    totalAmount: 2700000,
    depositPaid: 1000000,
    balanceDue: 1700000,
    specialRequests: "Arriving around 15:30 via taxi.",
    createdAt: "2026-08-20 18:20",
    folioId: "fol-007",
  }
];

export const INITIAL_FOLIOS: Folio[] = [
  {
    id: "fol-001",
    reservationId: "res-001",
    guestName: "Dr. Jonathan Lee",
    roomNumber: "101",
    items: [
      { id: "fi-101", date: "2026-08-23", description: "Room Charge - Deluxe King (Night 1)", category: "ROOM_CHARGE", amount: 1450000, postedBy: "NIGHT_AUDIT_AUTO" },
      { id: "fi-102", date: "2026-08-23", description: "The Heritage Grill - 2x Wagyu Ribeye & Wine", category: "FNB", amount: 890000, reference: "POS-ORD-4019", postedBy: "FNB_POS" },
      { id: "fi-103", date: "2026-08-24", description: "Maximuz Heritage Spa - 90m Balinese Massage", category: "SPA", amount: 650000, postedBy: "SPA_RECEPTION" },
      { id: "fi-104", date: "2026-08-24", description: "Minibar - 2x Bintang Beer & Gourmet Nuts", category: "MINIBAR", amount: 140000, postedBy: "HOUSEKEEPING" },
    ],
    payments: [
      { id: "pay-101", date: "2026-08-23", method: "CREDIT_CARD", amount: 2000000, referenceNo: "CC-VISA-8812", processedBy: "Dewi Lestari" }
    ],
    subtotal: 3130000,
    serviceCharge: 313000,
    tax: 344300,
    grandTotal: 3787300,
    totalPaid: 2000000,
    balance: 1787300,
    isClosed: false,
  },
  {
    id: "fol-003",
    reservationId: "res-003",
    guestName: "H. Salim Effendi",
    roomNumber: "105",
    items: [
      { id: "fi-301", date: "2026-08-22", description: "Room Charge - Garden Pool Villa (Night 1)", category: "ROOM_CHARGE", amount: 3500000, postedBy: "NIGHT_AUDIT_AUTO" },
      { id: "fi-302", date: "2026-08-23", description: "Room Charge - Garden Pool Villa (Night 2)", category: "ROOM_CHARGE", amount: 3500000, postedBy: "NIGHT_AUDIT_AUTO" },
      { id: "fi-303", date: "2026-08-23", description: "In-Villa Private Chef Dining Banquet", category: "FNB", amount: 2800000, reference: "POS-VILLA-09", postedBy: "CHEF_DIDI" },
      { id: "fi-304", date: "2026-08-24", description: "Express Laundry & Dry Cleaning (4 Garments)", category: "LAUNDRY", amount: 240000, postedBy: "HOUSEKEEPING" },
    ],
    payments: [
      { id: "pay-301", date: "2026-08-22", method: "BANK_TRANSFER", amount: 10500000, referenceNo: "BCA-TRF-99018", processedBy: "Victoria Wijaya" }
    ],
    subtotal: 10040000,
    serviceCharge: 1004000,
    tax: 1104400,
    grandTotal: 12148400,
    totalPaid: 10500000,
    balance: 1648400,
    isClosed: false,
  }
];

export const INITIAL_HOUSEKEEPING_TASKS: HousekeepingTask[] = [
  {
    id: "hk-101",
    roomNumber: "102",
    roomId: "rm-102",
    taskType: "CHECKOUT_TURNOVER",
    priority: "HIGH",
    status: "PENDING",
    assignedTo: "Ratna Sari",
    checklist: [
      { item: "Strip & replace bed sheets (Par 3 crisp cotton)", completed: false },
      { item: "Disinfect bathroom and replace 4x towels", completed: false },
      { item: "Restock guest amenities (Botanical shampoo, dental kit)", completed: false },
      { item: "Vacuum carpets and polish teak furniture", completed: false },
      { item: "Check minibar seal and inventory sheet", completed: false },
    ],
    notes: "Guest checking in today at 16:00. Fast turnaround required.",
  },
  {
    id: "hk-102",
    roomNumber: "203",
    roomId: "rm-203",
    taskType: "DAILY_REFRESH",
    priority: "NORMAL",
    status: "IN_PROGRESS",
    assignedTo: "Ratna Sari",
    startedAt: "2026-08-24 13:10",
    checklist: [
      { item: "Make bed & arrange decorative cushions", completed: true },
      { item: "Empty trash & replace liner", completed: true },
      { item: "Wipe down bathroom vanity & replace hand towel", completed: false },
      { item: "Replenish complimentary spring water (2 bottles)", completed: false },
    ],
    notes: "Guest is out attending seminar in meeting room.",
  },
  {
    id: "hk-103",
    roomNumber: "103",
    roomId: "rm-103",
    taskType: "INSPECTION",
    priority: "NORMAL",
    status: "VERIFIED",
    assignedTo: "Wayan Sudir",
    completedAt: "2026-08-24 11:15",
    inspectedBy: "Siti Rahmawati (Executive HK)",
    checklist: [
      { item: "Check bed corners and hospital fold alignment", completed: true },
      { item: "Inspect shower glass for water spots", completed: true },
      { item: "Verify AC temperature set to 22°C welcoming mode", completed: true },
      { item: "Confirm welcoming letter & fruit platter placed", completed: true },
    ],
    notes: "Passed 100% Quality Audit score.",
  },
  {
    id: "hk-104",
    roomNumber: "401",
    roomId: "rm-401",
    taskType: "TURNDOWN_SERVICE",
    priority: "URGENT",
    status: "PENDING",
    assignedTo: "Siti Rahmawati",
    checklist: [
      { item: "Draw blackout drapes and dim ambient lights to 20%", completed: false },
      { item: "Fold duvet corner and place artisan chocolates", completed: false },
      { item: "Place lavender pillow mist & bedside water carafe", completed: false },
      { item: "Lay bath mat and soft slippers bedside", completed: false },
    ],
    notes: "Tan Sri Khoo returns at 21:00. Ensure impeccable luxury presentation.",
  }
];

export const INITIAL_WORK_ORDERS: MaintenanceWorkOrder[] = [
  {
    id: "wo-001",
    ticketCode: "ENG-2608-304",
    roomNumber: "206",
    location: "Room 206 (Floor 2)",
    title: "Daikin Inverter AC Leaking & Low Cooling",
    category: "HVAC_AIR_CONDITIONING",
    priority: "CRITICAL_URGENT",
    status: "IN_PROGRESS",
    reportedBy: "Ratna Sari (Housekeeping)",
    assignedTechnician: "Agus Pratama",
    reportedAt: "2026-08-24 08:45",
    description: "Water condensation dripping from fan coil unit onto desk. Room marked Out of Order.",
    estimatedCost: 350000,
  },
  {
    id: "wo-002",
    ticketCode: "ENG-2608-305",
    roomNumber: "105",
    location: "Garden Pool Villa 105",
    title: "Pool Underwater LED Lighting Sensor Glitch",
    category: "ELECTRICAL",
    priority: "HIGH",
    status: "RESOLVED",
    reportedBy: "Made Wirya",
    assignedTechnician: "Bambang Wibowo",
    reportedAt: "2026-08-23 15:20",
    resolvedAt: "2026-08-24 10:00",
    description: "Timer relay stuck in daytime mode. Replaced smart switch controller with spare unit.",
    resolutionNotes: "Replaced relay PCB. Tested RGB lighting scenes with iPad controller.",
    estimatedCost: 180000,
  },
  {
    id: "wo-003",
    ticketCode: "ENG-2608-306",
    location: "Main Kitchen - Walk-in Chiller #2",
    title: "Door Gasket Seal Replacement & Temp Calibration",
    category: "PLUMBING",
    priority: "MEDIUM",
    status: "OPEN",
    reportedBy: "Chef Didi (Executive Chef)",
    assignedTechnician: "Agus Pratama",
    reportedAt: "2026-08-24 11:30",
    description: "Chiller door seal showing wear; internal temp drifting from 2°C to 5°C.",
    estimatedCost: 450000,
  }
];

export const INITIAL_CHANNELS: DepartmentChannel[] = [
  { id: "ch-ops", name: "general-ops", description: "Hotel-wide daily operational updates, VIP alerts & announcements", unreadCount: 2, icon: "Radio" },
  { id: "ch-fo", name: "front-office", description: "Check-in queues, arrivals, guest room moves & VIP requests", unreadCount: 1, icon: "Key" },
  { id: "ch-hk", name: "housekeeping", description: "Room release status, turnarounds, lost & found items", unreadCount: 0, icon: "Sparkles" },
  { id: "ch-eng", name: "engineering", description: "Facility tickets, HVAC maintenance & guest tech support", unreadCount: 3, icon: "Wrench" },
  { id: "ch-fnb", name: "f-and-b-banquet", description: "Restaurant tables, room service delivery & banquet events", unreadCount: 0, icon: "UtensilsCrossed" },
  { id: "ch-exec", name: "executive-mgmt", description: "Owner & GM briefings, revenue targets, audit reports", isPrivate: true, unreadCount: 0, icon: "ShieldAlert" },
];

export const INITIAL_MESSAGES: InternalMessage[] = [
  {
    id: "msg-001",
    channelId: "ch-ops",
    senderName: "Alexander Hartanto, CHA",
    senderRole: "General Manager",
    timestamp: "08:00 AM",
    content: "Good morning team. We are pacing at 84.2% occupancy today with 4 VIP arrivals. Tan Sri Khoo arrives in Penthouse 401 this evening. Let's ensure zero service friction across all touchpoints.",
    reactions: [{ emoji: "🙏", count: 8, users: ["Dewi", "Siti", "Bambang", "Victoria"] }, { emoji: "⭐", count: 5, users: ["Agus", "Wayan"] }],
  },
  {
    id: "msg-002",
    channelId: "ch-fo",
    senderName: "Dewi Lestari",
    senderRole: "Front Office Manager",
    timestamp: "09:30 AM",
    content: "Room 106 guest Amanda Valerie arriving early at 15:30. @housekeeping can we prioritize Suite 106 inspection before 14:00?",
    reactions: [{ emoji: "👍", count: 2, users: ["Siti"] }],
  },
  {
    id: "msg-003",
    channelId: "ch-hk",
    senderName: "Siti Rahmawati",
    senderRole: "Executive Housekeeper",
    timestamp: "09:35 AM",
    content: "Noted Dewi! Wayan is currently on Floor 1. Room 103 and 106 will be inspected and released to PMS by 13:30.",
  },
  {
    id: "msg-004",
    channelId: "ch-eng",
    senderName: "Bambang Wibowo",
    senderRole: "Chief Engineer",
    timestamp: "10:15 AM",
    content: "Update on Room 206 AC: New expansion valve installed. We are vacuuming lines and running cooling test. Estimated ready for HK turn by 14:30.",
    isUrgent: false,
  },
  {
    id: "msg-005",
    channelId: "ch-ops",
    senderName: "Victoria Wijaya, CPA",
    senderRole: "Financial Controller",
    timestamp: "11:00 AM",
    content: "Night Audit closed with Rp 64,800,000 gross revenue. RevPAR is up +14.2% MoM. Flash report is published in Finance module.",
    reactions: [{ emoji: "🎉", count: 6, users: ["Alexander", "Dewi", "Siti"] }],
  }
];

export const INITIAL_SHIFT_LOGS: ShiftLog[] = [
  {
    id: "sl-001",
    date: "2026-08-24",
    shift: "Morning (07:00-15:00)",
    dutyManager: "Dewi Lestari",
    department: "Front Office",
    keyNotes: "High check-out volume (12 rooms) processed smoothly between 08:00 - 11:30. Zero pending billing disputes. 3 VIP check-ins escorted to rooms.",
    pendingActions: [
      "Prepare welcoming keycard and welcome letter for Amanda Valerie (Room 106) due at 15:30.",
      "Follow up with Corporate Accounting regarding City Ledger invoice for Triputra Group.",
    ],
    isAcknowledged: true,
    acknowledgedBy: "Alexander Hartanto (GM)",
  },
  {
    id: "sl-002",
    date: "2026-08-24",
    shift: "Morning (07:00-15:00)",
    dutyManager: "Siti Rahmawati",
    department: "Housekeeping",
    keyNotes: "18 rooms completed, 4 stayovers in progress. Fresh linen consignment received from laundry vendor (Par 3 maintained).",
    pendingActions: [
      "Turndown service for Penthouse 401 scheduled strictly at 19:30.",
      "Inspect Suite 206 after Engineering releases the AC repair.",
    ],
    isAcknowledged: true,
    acknowledgedBy: "Dewi Lestari (FOM)",
  }
];

export const INITIAL_FNB_ITEMS: FnBItem[] = [
  { id: "fnb-01", name: "Australian Wagyu Ribeye MB7 (250g)", category: "Main Course", price: 420000, isAvailable: true, prepTimeMinutes: 25, description: "Served with truffle potato mousseline, charred asparagus & red wine jus." },
  { id: "fnb-02", name: "Heritage Nasi Goreng Buntut", category: "Main Course", price: 185000, isAvailable: true, prepTimeMinutes: 15, description: "Fragrant wok-fried rice with braised oxtail, sunny egg, melinjo crackers & house pickles." },
  { id: "fnb-03", name: "Pan-Seared Chilean Sea Bass", category: "Main Course", price: 360000, isAvailable: true, prepTimeMinutes: 20, description: "Citrus beurre blanc, baby carrots, saffron risotto." },
  { id: "fnb-04", name: "Truffle & Wild Mushroom Soup", category: "Appetizer", price: 95000, isAvailable: true, prepTimeMinutes: 10, description: "Creamy velouté, artisan garlic sourdough crisp." },
  { id: "fnb-05", name: "Maximuz Heritage Tiramisu", category: "Dessert", price: 85000, isAvailable: true, prepTimeMinutes: 10, description: "Mascarpone cream, espresso-soaked ladyfingers, Valrhona cocoa." },
  { id: "fnb-06", name: "Signature Smoked Old Fashioned", category: "Cocktail & Wine", price: 175000, isAvailable: true, prepTimeMinutes: 5, description: "Bourbon, Angostura bitters, oak wood smoke presentation." },
  { id: "fnb-07", name: "Single Origin Cold Brew (Aceh Gayo)", category: "Beverage", price: 65000, isAvailable: true, prepTimeMinutes: 5, description: "18-hour slow drip extraction, served over hand-carved crystal ice." },
];

export const INITIAL_FNB_ORDERS: FnBOrder[] = [
  {
    id: "ord-101",
    orderNumber: "ORD-2608-041",
    roomNumber: "101",
    orderType: "ROOM_SERVICE",
    guestName: "Dr. Jonathan Lee",
    items: [
      { item: INITIAL_FNB_ITEMS[0], quantity: 1, notes: "Medium rare, sauce on the side" },
      { item: INITIAL_FNB_ITEMS[6], quantity: 2 },
    ],
    status: "SERVED",
    totalAmount: 550000,
    placedAt: "2026-08-24 12:15",
  },
  {
    id: "ord-102",
    orderNumber: "ORD-2608-042",
    roomNumber: "105",
    orderType: "ROOM_SERVICE",
    guestName: "H. Salim Effendi",
    items: [
      { item: INITIAL_FNB_ITEMS[1], quantity: 2, notes: "Mild spicy" },
      { item: INITIAL_FNB_ITEMS[3], quantity: 2 },
      { item: INITIAL_FNB_ITEMS[4], quantity: 2 },
    ],
    status: "IN_DELIVERY",
    totalAmount: 730000,
    placedAt: "2026-08-24 13:00",
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: "inv-01", sku: "LIN-KNG-01", name: "Egyptian Cotton King Duvet Cover (400TC)", category: "Guest Room Linen", unit: "Pcs", currentStock: 94, parLevel: 120, reorderPoint: 40, unitCost: 450000, supplier: "Grand Luxe Textiles Bandung", lastRestocked: "2026-08-15" },
  { id: "inv-02", sku: "LIN-TWN-02", name: "Egyptian Cotton Twin Fitted Sheet (400TC)", category: "Guest Room Linen", unit: "Pcs", currentStock: 76, parLevel: 100, reorderPoint: 35, unitCost: 320000, supplier: "Grand Luxe Textiles Bandung", lastRestocked: "2026-08-15" },
  { id: "inv-03", sku: "AMN-BTH-01", name: "Botanical Sandalwood Body Wash (50ml)", category: "Bath Amenities", unit: "Bottles", currentStock: 340, parLevel: 600, reorderPoint: 150, unitCost: 18500, supplier: "Sensatia Luxury Hospitality", lastRestocked: "2026-08-10" },
  { id: "inv-04", sku: "AMN-DEN-02", name: "Eco Bamboo Dental Kit with Mint Paste", category: "Bath Amenities", unit: "Sets", currentStock: 110, parLevel: 500, reorderPoint: 150, unitCost: 12000, supplier: "GreenStay Amenities Bali", lastRestocked: "2026-08-01" },
  { id: "inv-05", sku: "FNB-COF-01", name: "Nespresso Compatible Arabica Pods (Grand Cru)", category: "Minibar Stock", unit: "Capsules", currentStock: 480, parLevel: 800, reorderPoint: 200, unitCost: 9500, supplier: "Java Roastery Specialty", lastRestocked: "2026-08-18" },
  { id: "inv-06", sku: "ENG-LED-01", name: "Warm White Dimmable LED Bulb E27 (7W)", category: "Engineering Spares", unit: "Units", currentStock: 18, parLevel: 50, reorderPoint: 20, unitCost: 48000, supplier: "Philips Lighting Distribution", lastRestocked: "2026-07-28" },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-001",
    poNumber: "PO-2026-08-104",
    supplier: "Sensatia Luxury Hospitality",
    category: "Bath Amenities",
    items: [
      { itemName: "Botanical Sandalwood Body Wash (50ml)", quantity: 500, unitCost: 18500, subtotal: 9250000 },
      { itemName: "Botanical Bergamot Shampoo (50ml)", quantity: 500, unitCost: 18500, subtotal: 9250000 },
    ],
    totalAmount: 18500000,
    status: "APPROVED",
    requestedBy: "Siti Rahmawati (Executive HK)",
    requestedDate: "2026-08-22",
  },
  {
    id: "po-002",
    poNumber: "PO-2026-08-105",
    supplier: "GreenStay Amenities Bali",
    category: "Bath Amenities",
    items: [
      { itemName: "Eco Bamboo Dental Kit with Mint Paste", quantity: 600, unitCost: 12000, subtotal: 7200000 }
    ],
    totalAmount: 7200000,
    status: "PENDING_GM_APPROVAL",
    requestedBy: "Siti Rahmawati (Executive HK)",
    requestedDate: "2026-08-24",
  }
];

export const INITIAL_STAFF: StaffMember[] = [
  { id: "stf-01", employeeId: "EMP-001", fullName: "Alexander Hartanto, CHA", role: "General Manager", department: "Management", shift: "General", status: "ON_DUTY", phone: "+62 811 200 900", email: "gm@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80", performanceScore: 98 },
  { id: "stf-02", employeeId: "EMP-002", fullName: "Dewi Lestari", role: "Front Office Manager", department: "Front Office", shift: "Morning", status: "ON_DUTY", phone: "+62 812 345 678", email: "fom@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80", performanceScore: 96 },
  { id: "stf-03", employeeId: "EMP-003", fullName: "Siti Rahmawati", role: "Executive Housekeeper", department: "Housekeeping", shift: "Morning", status: "ON_DUTY", phone: "+62 813 456 789", email: "hk.exec@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80", performanceScore: 95 },
  { id: "stf-04", employeeId: "EMP-004", fullName: "Bambang Wibowo, ST", role: "Chief Engineer", department: "Engineering", shift: "Morning", status: "ON_DUTY", phone: "+62 815 678 901", email: "engineering@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80", performanceScore: 92 },
  { id: "stf-05", employeeId: "EMP-005", fullName: "Victoria Wijaya, CPA", role: "Financial Controller", department: "Finance & Accounting", shift: "General", status: "ON_DUTY", phone: "+62 817 890 123", email: "finance@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80", performanceScore: 99 },
  { id: "stf-06", employeeId: "EMP-006", fullName: "Wayan Sudir", role: "Senior Room Attendant", department: "Housekeeping", shift: "Morning", status: "ON_DUTY", phone: "+62 819 112 334", email: "wayan.s@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80", performanceScore: 94 },
  { id: "stf-07", employeeId: "EMP-007", fullName: "Ratna Sari", role: "Room Attendant", department: "Housekeeping", shift: "Morning", status: "ON_DUTY", phone: "+62 818 223 445", email: "ratna.s@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80", performanceScore: 91 },
  { id: "stf-08", employeeId: "EMP-008", fullName: "Agus Pratama", role: "HVAC & Electrical Technician", department: "Engineering", shift: "Morning", status: "ON_DUTY", phone: "+62 816 334 556", email: "agus.p@maximuz-hotel.com", avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80", performanceScore: 90 },
];

export const INITIAL_NIGHT_AUDITS: NightAuditRecord[] = [
  {
    id: "na-2026-08-23",
    auditDate: "2026-08-23",
    auditorName: "Victoria Wijaya, CPA",
    totalOccupiedRooms: 15,
    occupancyRatePercent: 83.3,
    totalRoomRevenue: 52400000,
    totalFnbRevenue: 9800000,
    totalOtherRevenue: 2600000,
    totalGrossRevenue: 64800000,
    adr: 1450000,
    revPar: 1208333,
    pendingFoliosResolved: 4,
    discrepanciesCount: 0,
    completedAt: "2026-08-24 03:15",
    status: "SUCCESSFUL",
  },
  {
    id: "na-2026-08-22",
    auditDate: "2026-08-22",
    auditorName: "Victoria Wijaya, CPA",
    totalOccupiedRooms: 14,
    occupancyRatePercent: 77.8,
    totalRoomRevenue: 48900000,
    totalFnbRevenue: 8400000,
    totalOtherRevenue: 1900000,
    totalGrossRevenue: 59200000,
    adr: 1420000,
    revPar: 1104761,
    pendingFoliosResolved: 3,
    discrepanciesCount: 0,
    completedAt: "2026-08-23 03:00",
    status: "SUCCESSFUL",
  }
];
